name: build-pr
on:
  pull_request_target:
    types: [assigned, opened, edited, synchronize, reopened]
    branches:
      - main
jobs:
  build-and-deploy-pr:
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y rsync

      - name: Get the pull request
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Save XML
        run: |
          mkdir /tmp/pr-sources
          for f in src overview schema xproc; do
            mkdir /tmp/pr-sources/$f
            rsync -ar $f/ /tmp/pr-sources/$f/
          done

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update XML
        run: rsync -var /tmp/pr-sources/ ./

      - name: Build specifications
        run: |
          ./gradlew

      - name: Deploy
        if: ${{ env.HAVE_ACCESS_TOKEN == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          target-folder: /pr/${{ github.event.number }}
